GET http://localhost:4000/getusers

###
GET http://localhost:4000/getuser/3

###
POST http://localhost:4000/create-user
Content-Type: application/json

{
    "id":3,
    "name":"Afshan",
    "age":19
}


###
PUT http://localhost:4000/update-user
Content-Type: application/json

{
    "id":1,
    "name":"ravi sharma",
    "age":34
}

###
DELETE http://localhost:4000/remove-user/2


###
GET http://localhost:4000/getproducts

###
GET http://localhost:4000/getproduct/5

###
POST http://localhost:4000/create-product

